### ISSUE TITLE
ninjax.py line 207 _fun(*args, *kwargs) -> _fun(*args, **kwargs) ? 

### ISSUE THREAD

**Issue by intuinno** [danijar/ninjax#11]
Hi, Danijar. 

I appreciate your contribution for the research so far.  I have a question about the ninjax.py line: 207 code. 

```
  if not has_aux:
    fun = lambda *args, _fun=fun, **kwargs: (_fun(*args, *kwargs), {})
    fun = pure(fun, nested=True)
```

My question is  whether _fun(*args, *kwargs) is a typo for _fun(*args, **kwargs).  

Thank you. 

Regards

Deokgun

**Comment by intuinno** [comment]
For the record, I think this is not a bug. 

The lambda function is trying to change keyword arguments to positional arguments such that the positional arguments can come before the keyword arguments in the later part of the execution.

**Comment by danijar** [comment]
Yes, that looks like a bug. Thanks for pointing it out!
