### ISSUE TITLE
Compiler error for file "quickstart.py" - __annotation__ error 

### ISSUE THREAD

**Issue by realjoenguyen** [danijar/ninjax#7]
Hi, 

Thank you for the nice framework, 

I want to run your file "quickstart.py" and got the following compiler error:

> File "/nfs/hpc/share/nguyejoe/dynalang/ninjax_test/quickstart.py", line 8, in <module>
    import ninjax as nj
  File "/nfs/hpc/share/nguyejoe/dynalang/ninjax_test/ninjax/__init__.py", line 1, in <module>
    from .ninjax import __version__
  File "/nfs/hpc/share/nguyejoe/dynalang/ninjax_test/ninjax/ninjax.py", line 471, in <module>
    class Module(object, metaclass=ModuleMeta):
  File "/nfs/hpc/share/nguyejoe/dynalang/ninjax_test/ninjax/ninjax.py", line 418, in __new__
    k: getattr(cls, k) for k, v in cls.__annotations__.items()
AttributeError: type object 'Module' has no attribute '__annotations__'

The error starts from class `Module` in ninjax.py where it hasn't had annotation information yet. Appreciate your help with this issue.

**Comment by danijar** [comment]
I'm not sure if that Python version has class annotations yet? All tests including the quick start ecample
